{% set name = "cdutil" %}
{% set version = "8.1" %}

package:
    name: cdutil
    version: {{ version }}

source:
    url: https://github.com/CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 37d3dfa2202cab4e42a9c04cb1956dffe2146c5594fed04f6c32c91554c84b53


build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cdat_info
  run:
    - python
    - cdms2
    - genutil
    - cdat_info >=8.1

test:
  commands:
    - export CDAT_ANONYMOUS_LOG=false && python -c "import cdutil"

about:
    home:  http://github.com/CDAT/cdutil
    summary: A set of tools to manipulate climate data
    license: BSD
    license_file: bsd-3-clause.txt

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
