{% set name = "cdutil" %}
{% set version = "3.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdutil/archive/master.tar.gz
    sha256: a3cb57bcee0ab17d9d4100596d8f11d693d4f39708311c3a982239d27f6e54d5

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - numpy
    - udunits2
    - genutil

test:
  command:
    - export UVCDAT_ANONYMOUS_LOG=false && python -c "import cdutil"

about:
    home:  http://github.com/UV-CDAT/cdutil
    license: 'CCLRC'
    license_file: LICENSE
    summary: 'Climate Data Related Utitilites for the Community Data Analysis Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
