{% set name = "cdutil" %}
{% set version = "2.10" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: f74c8f2d9ca547e8a925835486ea995775e99badf1d8fe24477554b32de2e733
    

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - numpy
    - udunits2
    - genutil

test:
  command:
    - export UVCDAT_ANONYMOUS_LOG=false && python run_tests.py -v2

about:
    home:  http://github.com/UV-CDAT/cdutil
    license: 'CCLRC'
    license_file: LICENSE
    summary: 'Climate Data Related Utitilites for the Community Data Analysis Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
