{% set name = "cdutil" %}
{% set version = "8.1" %}

package:
    name: cdutil
    version: {{ version }}

source:
    url: https://github.com/CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 20ea2870902fb0eeefe54fb49294e6707c555dd75a3b797d622357b2073a297a


build:
  number: 1
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cdat_info >=8.1
  run:
    - python
    - cdms2
    - genutil >=8.1.1
    - cdat_info >=8.1

test:
  commands:
    - export CDAT_ANONYMOUS_LOG=false && python -c "import cdutil"

about:
    home:  http://github.com/CDAT/cdutil
    summary: A set of tools to manipulate climate data
    license: BSD
    license_file: bsd-3-clause.txt

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
