package:
    name: cdutil
    version: 8.1

source:
    url: https://github.com/CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 37d3dfa2202cab4e42a9c04cb1956dffe2146c5594fed04f6c32c91554c84b53


build:
  number: 0
  noarch: python
  script: python setup.py install
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - genutil

about:
    home:  http://github.com/CDAT/cdutil
    summary: A set of tools to manipulate climate data
    license: BSD
    license_file: bsd-3-clause.txt

